version: "3.9"
services:
  user-service:
    image: user-service:1.0 # Using the built image instead of building from context
    ports:
      - "3001:3000"
    env_file:
      - ./user-service/.env
    depends_on:
      - mongodb

  recovery-plan-services:
    build:
      context: ./recovery-plan-services
    ports:
      - "3002:3000"
    env_file:
      - ./recovery-plan-services/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
